name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.3"
          cache: true

      - name: Build
        run: ./bin/build

      - name: Test
        run: ./bin/test
